### ISSUE TITLE
Watch option in docker compose

### ISSUE THREAD

**Issue by guillaumedev** [dotronglong/faker#34]
Hi there, 

I'd like to use watch option in docker compose, is there any easy way to do that ? 

Thank you!

**Comment by yarkovaleksei** [comment]
@guillaumedev Hi! I had the same issue and I solved the problem like this.

```yml
services:
    api-mocks:
        image: dotronglong/faker:2.1.4
        command: [ "-Dserver.port=3030", "-Dfaker.source=/app/mocks", "-Dfaker.watch=true", "-jar", "/app/faker.jar" ]
        volumes:
            - ../app/mocks:/app/mocks:ro
```
